---
include:
  # ==============================
  # R側 (Central)
  # ==============================
  # トラックパッド版
  - board: seeeduino_xiao_ble//zmk
    shield: sosho_R_trackpad rgbled_adapter
    artifact-name: sosho_R_trackpad

  # トラックボール版
  - board: seeeduino_xiao_ble//zmk
    shield: sosho_R_trackball rgbled_adapter
    artifact-name: sosho_R_trackball

  # ==============================
  # L側 (Peripheral)
  # ==============================
  # トラックパッド版
  - board: seeeduino_xiao_ble//zmk
    shield: sosho_L_trackpad rgbled_adapter
    artifact-name: sosho_L_trackpad

  # トラックボール版
  - board: seeeduino_xiao_ble//zmk
    shield: sosho_L_trackball rgbled_adapter
    artifact-name: sosho_L_trackball

  # ==============================
  # 設定リセット用
  # ==============================
  - board: seeeduino_xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset
