manifest:
  defaults:
    revision: v0.19.0
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: elekit-official
      url-base: https://github.com/elekit-official
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.19.0
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.19.0
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: v0.19.0
    - name: zmk_encoder
      remote: elekit-official
      revision: v0.19.0
      path: modules/zmk_encoder
  self:
    path: config
